### ISSUE TITLE
addFiles

### ISSUE THREAD

**Issue by brain2xml** [pqina/jquery-filepond#11]
Hi!

When I upload files to server i had files ids in hidden field, and that is working normal.

Problem when i open page to edit and have files id. i try to use addFiles

```
pond.setOptions({

        server: {
            url: './',
            process: {
                headers: {
                    "X-CSRF-Token": document.querySelector('input[name=_token]').value,
                },
                url: '/uploadimage',
            },
            revert: './a/',
            revert: './r/',
            load: './l/',
            fetch: './f/'
        },
    });


pond.addFiles([{
  serverId:1235,
            options: {
                type: 'local'
            }
}]);

```
it makes xdr http://bloodyland.info/news/load/%7B%22serverId%22%3A1235%2C%22options%22%3A%7B%22type%22%3A%22local%22%7D%7D

plase give my example to show already upload file in list 

I do not to need upload them again, just have delete options

**Comment by rikschennink** [comment]
Duplicate of https://github.com/pqina/filepond/issues/378
