### ISSUE TITLE
Trigger `revert` while initializing with uploaded files

### ISSUE THREAD

**Issue by AnandPilania** [pqina/jquery-filepond#16]
Hello fellow developer!

💡 If you want to submit a feature request, go right ahead!

🐜 If you've found a bug, please use the template below to report it.

**The more details you provide, the more inclined other developers are to help you and the faster the problem is resolved.**

If you think the issue is related FilePond itself and not the jQuery library or adapter, please submit the issue in the FilePond repository.

Please format code snippets using backticks and don't forget to set the appropriate language.
https://help.github.com/articles/creating-and-highlighting-code-blocks/

### Summary
Filepond triggering `revert` action while submitting the form where Filepond is initialized with uploaded files;

### How to reproduce
JSON: 
```
'source' => 1,
        'options' => [
            'type' => 'local',
            'file' => [
                'name' => 'abc',
                'size' => 100,
                'type' => 'image/...',
            ],
            'metadata' => [
                'poster' => 'file_path',
            ],
        ],
```

COMMON: 
```
(function($) {
    $.fn.filepond.registerPlugin(
        FilePondPluginFileValidateSize,
        FilePondPluginFileValidateType,
    );

    var filepondOptions = {
        credits: false,
        server: {
            url: '/filepond',
            process: '/upload',
            revert: '/destroy',
            restore: '/load?id=',
            load: '/load?id=',
        }
    };

    $.fn.filepond.setDefaults(filepondOptions);
})(jQuery);
```

INIT ELEMENTS: 
```
files = [json];
$('#input_file').filepond({files: files})
```

Now, everything works fine, except, while submitting the form, it trigger the `revert` method and send an `delete` ajax request to the server.

### Expected behaviour
`revert` or `delete` method/request should not be triggered automatically, it must be triggered by the user while clicking the `revert` button

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS / Windows / iOS / Linux / ...
| Device       | iPhone SE / Galaxy Note 9 / ...
| Browser      | Safari 11.1.1 / Edge 15 / ...

**Comment by rikschennink** [comment]
Please provide a test case on https://codesandbox.io/ happy to take a look.

**Comment by AnandPilania** [comment]
@rikschennink I tried to replicate the scenario at codesandbox but its working fine there. Can I face that issue when Filepond is re-initialized with files at same element/multiple elements?

**Comment by rikschennink** [comment]
> Can I face that issue when Filepond is re-initialized with files at same element/multiple elements?

I'm not sure what you mean by that, please elaborate

As the issue can't be reproduced in a separate environment I'll close it for now.
