### ISSUE TITLE
onreorderfiles Event is not triggering

### ISSUE THREAD

**Issue by yongkyali** [pqina/jquery-filepond#17]
### Summary
Hello, thank you for the amazing library! I have an issue with `reorderfiles` event it's not trigger whenever I re-order the items. Other events are working well without any issue. Tried this with Firefox and faced with same issue.

### How to reproduce
```
<input id="images" class="filepond-custom-container" />

<script>
$('#images').filepond({
        name: 'chapter_images[]',
        allowMultiple: true,
        storeAsFile: true,
        required: true,
        allowReorder: true,
        itemInsertLocation: 'after',
});

// Working well
$('#images').on('FilePond:removefile', function (e) {
        console.log('remove is triggered', e);
});

// Not working
$('#images').on('FilePond:onreorderfiles', function (e) {
        console.log('the collection is just being reordered', e);
});
</script>
```

### Expected behaviour
Event should be triggered.

### Additional information

| Environment  | Version
|------------- | -----------
| OS           | MacOS Monterey
| Device       | Mac Mini M1
| Browser      | Chrome Version 95.0.4638.69 (Official Build) (arm64)

**Comment by rikschennink** [comment]
It's `reorderfiles` instead of `onreorderfiles`

https://codesandbox.io/s/filepond-reorder-9v9bt?file=/src/index.js

**Comment by yongkyali** [comment]
But it written as `onreorderfiles` the current documentation. 
![Screen Shot 2021-11-06 at 00 17 40](https://user-images.githubusercontent.com/22522732/140552075-fa1e27a7-b63d-43c3-9765-50126b7f0791.png)

Correct me if I'm wrong. Because I tried to do it with plain javascript as written (which is `onreorderfiles`) and also not working.

**Comment by rikschennink** [comment]
I think that is a typo, looking into it.

**Comment by rikschennink** [comment]
Fixed the typo, should indeed be `activefile` and `reorderfiles` updated the codesandbox demo as well.
