### ISSUE TITLE
Não estou conseguindo trazer as imagens que estao no banco

### ISSUE THREAD

**Issue by 1JP** [pqina/jquery-filepond#19]
Estou tentando trazer as fotos que estão no banco(Mysql) sem sucesso, estou usando Laravel 8, jquery e filepond. 
Abaixo esta o meu código.

$.fn.filepond.registerPlugin(
            FilePondPluginFileEncode,
            FilePondPluginImagePreview,
            FilePondPluginImageResize,
            FilePondPluginFileValidateType,
            FilePondPluginImageExifOrientation,
            FilePondPluginImageCrop,
            FilePondPluginImageTransform,
            FilePondPluginFileMetadata,
            FilePondPluginFileRename
        );

        $.fn.filepond.setOptions({
            'name': 'file[]',
            'server': {
                process: {
                    url: '{{ route('uploads') }}',
                    headers: {
                        "X-CSRF-TOKEN": "{{ csrf_token() }}"
                    },
                    onload: (response) => {
                        folders.push(response);
                    },
                },
                load: {
                    url: '{{ route('fetch', $produto->id) }}',
                    method: 'GET',
                    headers: {
                        'Access-Control-Expose-Headers': 'Content-Disposition',
                        'Content-Disposition': 'inline; filename="my-file.jpg"',
                    },
                    withCredentials: false,
                    timeout: 7000,
                    onload: function(response) {
                        console.log(response)
                    },
                    onerror: function (res) {
                        console.log(res)
                    }
                }

            },

        });
        // Turn input element into a pond
        $('.my-pond').filepond();

        $('.my-pond').filepond({
            'allowMultiple': true,
            'labelIdle': `<h5 class="text-center text-muted"><i class="fa fa-fw fa-picture-o pr-4 fa-4x" style="font-size: 100px;"></i></h5>
                        <h5 class="text-center">Arraste e solte suas Imagens aqui</h5>
                           <p class="text-center">Máximo de 10 imagens. Tamanho máximo 3MB.&nbsp;<br>Para maior qualidade envie imagens no formato JPG ou PNG.</p>`,
            'allowReorder': true,
            'maxFileSize': '3MB',
            'maxFiles': 10,
            'imagePreviewMaxHeight': 150,
            'allowFileRename': true,
            'allowImagePreview': true,
            'instantUpload': true,
            //'acceptedFileTypes': ['image/png','image/jpg'],
            'labelFileTypeNotAllowed': 'Só é permitido imagens png e jpg',

        });

**Comment by rikschennink** [comment]
Closed because doesn't match issue template.
