### ISSUE TITLE
How to set the default file url?

### ISSUE THREAD

**Issue by wangooooooo** [pqina/jquery-filepond#2]
When editing an image record that has already been uploaded, I do not know how to set the default image url.
(Sorry, my English is very poor)

**Comment by rikschennink** [comment]
Hi @wangooooooo I'm not sure what you mean with "default image url", can you elaborate?

**Comment by wangooooooo** [comment]
When the user edits an object that contains a picture,I would like to show them the recently uploaded picture and give them the option to delete that one and upload another.

**Comment by wangooooooo** [comment]
![](http://ol587bfvt.bkt.clouddn.com/369004336008056123.jpg)

**Comment by rikschennink** [comment]
@wangooooooo you can use the `files` array to set the currently uploaded files. See the [setting initial files](https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files) entry in the docs.

**Comment by wangooooooo** [comment]
Thanks for being so responsive.
