### ISSUE TITLE
Upload button is not visible 

### ISSUE THREAD

**Issue by ghost** [pqina/jquery-filepond#3]
Hi 

Hope you are doing well!

I really like your jquery-filepond it's really good and user-friendly. I am facing the issue after browser the image i am not getting an upload button.

It will be very grateful if you can help me with this.
I am also attaching an image of how it's looking after I upload the file or images

![capture](https://user-images.githubusercontent.com/36707348/43606303-f5ff175a-9668-11e8-8553-e4e5fffc56dd.PNG)

**Comment by rikschennink** [comment]
Have you configured the `server` property?

**Comment by ghost** [comment]
Yes i have also downloaded all the file from GitHub (link to the folder which i have downloaded  all the file:https://github.com/pqina/filepond)

Also when i downloaded i haven't found any index.php or index.html file.

So it would be grateful if you could send me a link to any of the file.

**Comment by rikschennink** [comment]
I think this boilerplate might be the starting point you’re looking for:
https://github.com/pqina/filepond-boilerplate-php

Conversion to jQuery should be quite straightforward.

**Comment by ghost** [comment]
hey, I am using this software *Slim Image Cropper.* Is it possible to fetch
the image from one folder who is having multiple image files?
I mean in the code we can just fetch the image by hardcoding the file path
and fetch it from a folder. Is there any chances that we can select an
image from the folder.

**Comment by rikschennink** [comment]
I'm not sure what you mean, is this related to the original issue?

**Comment by ghost** [comment]
Nope.Its realted to image manager.Is tgere any possiblity that i can fetch the any image of my choice  from the folder

**Comment by rikschennink** [comment]
Which image manager? And what folder?

**Comment by ishaiavrahami** [comment]
any update ?
