### ISSUE TITLE
how to raise error on process

### ISSUE THREAD

**Issue by bakamaru** [pqina/jquery-filepond#4]
I'm using jquery filepond on my project and i'm trying to raise error on process's onload 
  process: {
                    url: '/api/v1/fileuploader/upload',
                    method: 'POST',                 
                    timeout: 7000,
                    onload: function (response) {
                        console.log(response,this)
                        if (response.Code == 200) {
                           //on successful save
                            return response.Data;
                        } else {
                                 //on saving failed on server/i've done validation in server
                                 //todo raise on error sothat view so upload error..
                            return false;
                        }
                    },
                    onerror: null

guide me.

**Comment by rikschennink** [comment]
Apparently, your server responds with a 200 status code even when there's been an error. The server should return an error status, FilePond will then automatically populate the error value in the `onprocessfile` callback.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by bakamaru** [comment]
I got your views but in my api server even on error we respond to caller with 500 as internal code but 200 as httpstatus code and status.
if it can't be done from client side,I'll have to create as your guides.
Thanks.

**Comment by rikschennink** [comment]
Then you'll have to set up a custom processing method, see this entry in the docs:
https://pqina.nl/filepond/docs/patterns/api/server/#advanced
