### ISSUE TITLE
How to reload already uploaded files from server?

### ISSUE THREAD

**Issue by bakamaru** [pqina/jquery-filepond#5]
I'm trying reload and show files ,I tried to extend
```
load: {
                    url: '/api/v1/fileuploader/load',
                    method: 'GET',
                    onload: function(response) {
                    
                    },
                    onerror: function (response) {
                     
                    }
                }
```
but problem is load api not making any requests.
how do i invoke load functionality manually?

**Comment by rikschennink** [comment]
See this entry on the `load` end point in the server docs: 
https://pqina.nl/filepond/docs/patterns/api/server/#load

And this entry on setting initial files: 
https://pqina.nl/filepond/docs/patterns/api/filepond-object/#setting-initial-files

In short, you need to set the existing files to the `files` property and mark them as type `local`.

**Comment by AnandPilania** [comment]
hi, I populate the files, but while submitting the form, its triggers the `revert` method automatically.
JSON 
```
'source' => 1,
        'options' => [
            'type' => 'local',
            'file' => [
                'name' => 'abc',
                'size' => 100,
                'type' => 'image/...',
            ],
            'metadata' => [
                'poster' => 'file_path',
            ],
        ],
```
