### ISSUE TITLE
Pass path back to delete button

### ISSUE THREAD

**Issue by mstahlmann** [pqina/jquery-filepond#7]
Jquery filepond. Using JQuery on an hbs page and uploading to a Node.js api. On the backend the photo is being saved to a user specific folder. Is there a way I can pass the path back so the filepond delete button works. I can also set a custom endpoint that deletes based on the user. I just didn't see in the docs how to do this with the jquery version.

**Comment by rikschennink** [comment]
Hi, I'm not sure what you want to achieve, can you elaborate

**Comment by mstahlmann** [comment]
I think I figured it out from your docs. I wanted to create 2 instances that had 2 different upload urls. I was confused about the options. I saw in the docs that you have two levels of options. Page level then another at the item level. The latter was optional so I didn’t notice it in the examples. I will try initializing the input element with the optional options included.

**Comment by mstahlmann** [comment]
Actually still having this issue. Here is the code

  FilePond.registerPlugin(FilePondPluginFileValidateSize);
    FilePond.registerPlugin(FilePondPluginImagePreview);
    FilePond.registerPlugin(FilePondPluginImageExifOrientation);
    const inputElement = document.querySelector("#header-pond");
    pond = FilePond.create(inputElement);
    pond.setOptions({
        server: `${base_url}/api/profilephoto`
    })


I need to create an additional uploader that points to a different route. How can this be achieved?

**Comment by rikschennink** [comment]
I guess this solved it: https://github.com/pqina/filepond/issues/216#issuecomment-460360588
